// <auto-generated />
using System;
using ManagePeople.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagePeople.DAL.Migrations
{
    [DbContext(typeof(ManagePeopleContext))]
    [Migration("20240308173726_Seeders")]
    partial class Seeders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManagePeople.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = new Guid("53194997-f61f-4f35-8e89-57a5b4935313"),
                            FirstName = "Josephine",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("e6e5ca24-4885-4c0c-937f-33ca348ab87d"),
                            FirstName = "Michael",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("84394d0f-bd4a-4c72-ae63-54b737d752c9"),
                            FirstName = "Daniel",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = new Guid("e1febb04-11c6-466b-8ff8-6d224dc512a2"),
                            FirstName = "Charles",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = new Guid("1818333e-e018-4937-820b-837ab193a5ac"),
                            FirstName = "Samuel",
                            LastName = "Donet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
